### ISSUE TITLE
iframe parser bug

### ISSUE THREAD

**Issue by iteratelance** [iterateco/iterate-media#2]
http://192.168.200.210:3000/parse?source=%3Ciframe%20width=%22560%22%20height=%22315%22%20src=%22https://www.youtube.com/embed/t7PGI0zfhLI?ecver=1%22%20frameborder=%220%22%20allowfullscreen%3E%3C/iframe%3E

Original source as follows but if using GET urls will be url encoded when sent to the API
<iframe width="560" height="315" src="https://www.youtube.com/embed/t7PGI0zfhLI?ecver=1" frameborder="0" allowfullscreen></iframe>

**Comment by sittitep** [comment]
it seems like that this video does not exist anymore
